# Generated by Django 2.2 on 2019-11-16 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description Product')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='image')),
                ('category', models.ForeignKey(default='other', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='webapp.Category', verbose_name='Product category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=2000, verbose_name='review')),
                ('assessment', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1, verbose_name='assessment')),
                ('author', models.ForeignKey(default=webapp.models.get_admin, on_delete=django.db.models.deletion.PROTECT, related_name='tracker_by', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='webapp.Product', verbose_name='product')),
            ],
        ),
    ]
